"""Public clustering configuration with reviewed-data calibrated defaults."""

from __future__ import annotations

from dataclasses import dataclass

from image_clustering.clustering._config_schema import ClusterConfig as _ClusterConfig


@dataclass(frozen=True)
class ClusterConfig(_ClusterConfig):
    """Validated clustering thresholds calibrated for large physical occlusions."""

    contradiction_text_min_ink_mismatch_tiles_fraction: float = 0.09

    # SIFT remains the primary registration. This fallback is deliberately limited
    # to same-orientation, small-motion captures and runs only after SIFT fails.
    ecc_fallback_enabled: bool = True
    ecc_min_correlation: float = 0.30
    ecc_max_rotation_degrees: float = 5.0
    ecc_max_translation_fraction: float = 0.18
    ecc_max_iterations: int = 100
    ecc_epsilon: float = 0.000001
    ecc_gaussian_filter_size: int = 5

    # Avoid full ECC on obviously unrelated pages. A fallback attempt requires a
    # bounded small-motion affine seed, enough exact descriptor matches, or coarse
    # phase-correlation evidence. Content scoring remains at full resolution.
    ecc_coarse_dimension: int = 192
    ecc_working_dimension: int = 384
    ecc_min_phase_correlation: float = 0.12
    ecc_min_descriptor_matches: int = 50

    # The continuous score is a recall-oriented review signal. It never bypasses
    # deterministic acceptance or hard-contradiction graph safeguards. The raw
    # synthetic classifier is additionally gated by real physical-occlusion
    # evidence: most text mismatch must lie inside one contiguous candidate while
    # the registered text channel outside that candidate remains substantially
    # stable.
    occlusion_candidate_probability_threshold: float = 0.08
    occlusion_evidence_min_ink_mismatch_capture: float = 0.15
    occlusion_evidence_full_ink_mismatch_capture: float = 0.75
    occlusion_evidence_min_localization_contrast: float = 0.03
    occlusion_evidence_full_localization_contrast: float = 0.35
    occlusion_evidence_min_inside_unmatched_ink_union_fraction: float = 0.35
    occlusion_evidence_full_inside_unmatched_ink_union_fraction: float = 0.70
    occlusion_evidence_distributed_outside_union_fraction: float = 0.20
    occlusion_evidence_distributed_outside_tiles_fraction: float = 0.55
    occlusion_evidence_distributed_penalty: float = 0.05

    # Near-background sheets can erase text while producing weak grayscale
    # residuals. When no residual component survives, infer one rectangular block
    # only from a dense, contiguous band of text-channel mismatch. The final
    # exterior-agreement and record-replacement gates remain authoritative.
    occlusion_ink_block_row_density: float = 0.40
    occlusion_ink_block_column_density: float = 0.35
    occlusion_ink_block_min_occupancy: float = 0.45
    occlusion_ink_block_min_width_fraction: float = 0.35
    occlusion_ink_block_min_rows: int = 3
    occlusion_ink_block_max_gap: int = 1

    # At reduced working resolutions, distributed handwriting replacement can
    # satisfy the broad material-change shortcut and make both pages look fully
    # occluded. A page-wide state escapes this veto only with clearly stronger
    # smooth material contrast or denser inside text replacement.
    occlusion_full_page_text_min_ink_mismatch_tiles_fraction: float = 0.55
    occlusion_full_page_text_max_material_median: float = 0.08
    occlusion_full_page_text_max_inside_unmatched_ink_union_fraction: float = 0.60

    # Extreme material changes may hide most content. When the remaining exterior
    # is dirty, require stronger identity support before creating an automatic edge.
    occlusion_dirty_exterior_min_feature_overlap: float = 0.15
    occlusion_dirty_exterior_min_alignment_score: float = 0.55
    occlusion_dirty_exterior_min_unmatched_ink_union_fraction: float = 0.10
    occlusion_dirty_exterior_min_ink_mismatch_tiles_fraction: float = 0.40

    # Automatic graph edges need plausible capture-sequence proximity. Pairs beyond
    # this filename suffix gap are retained as review candidates, not auto-linked.
    automatic_link_max_numeric_filename_gap: int = 12
    automatic_link_require_same_filename_prefix: bool = True
    automatic_link_allow_full_page_ecc: bool = False
    # Physical-occlusion evidence may be generated by a different filled copy of
    # the same printed form. Automatic edges therefore require materially stronger
    # document-specific feature overlap than review-candidate detection.
    automatic_link_min_physical_occlusion_feature_overlap: float = 0.35

    # Exact runtime caches. Working-image caching avoids source decode on warm runs;
    # pair caching checkpoints complete comparisons for instant restart/replay.
    cache_pairs: bool = True
    cache_working_images: bool = True
    feature_cache_compressed: bool = True

    def __post_init__(self) -> None:
        """Validate base thresholds and recall-first registration settings."""
        super().__post_init__()
        for name in (
            "ecc_min_correlation",
            "ecc_max_translation_fraction",
            "ecc_min_phase_correlation",
            "occlusion_candidate_probability_threshold",
            "occlusion_evidence_min_ink_mismatch_capture",
            "occlusion_evidence_full_ink_mismatch_capture",
            "occlusion_evidence_min_localization_contrast",
            "occlusion_evidence_full_localization_contrast",
            "occlusion_evidence_min_inside_unmatched_ink_union_fraction",
            "occlusion_evidence_full_inside_unmatched_ink_union_fraction",
            "occlusion_evidence_distributed_outside_union_fraction",
            "occlusion_evidence_distributed_outside_tiles_fraction",
            "occlusion_evidence_distributed_penalty",
            "occlusion_ink_block_row_density",
            "occlusion_ink_block_column_density",
            "occlusion_ink_block_min_occupancy",
            "occlusion_ink_block_min_width_fraction",
            "occlusion_full_page_text_min_ink_mismatch_tiles_fraction",
            "occlusion_full_page_text_max_material_median",
            "occlusion_full_page_text_max_inside_unmatched_ink_union_fraction",
            "occlusion_dirty_exterior_min_feature_overlap",
            "occlusion_dirty_exterior_min_alignment_score",
            "occlusion_dirty_exterior_min_unmatched_ink_union_fraction",
            "occlusion_dirty_exterior_min_ink_mismatch_tiles_fraction",
            "automatic_link_min_physical_occlusion_feature_overlap",
        ):
            value = getattr(self, name)
            if not 0.0 <= value <= 1.0:
                raise ValueError(f"{name} must be in [0, 1], got {value}")
        if (
            self.occlusion_evidence_full_ink_mismatch_capture
            <= self.occlusion_evidence_min_ink_mismatch_capture
        ):
            raise ValueError(
                "occlusion evidence full ink capture must exceed its minimum"
            )
        if (
            self.occlusion_evidence_full_localization_contrast
            <= self.occlusion_evidence_min_localization_contrast
        ):
            raise ValueError(
                "occlusion evidence full localization contrast must exceed its minimum"
            )
        if (
            self.occlusion_evidence_full_inside_unmatched_ink_union_fraction
            <= self.occlusion_evidence_min_inside_unmatched_ink_union_fraction
        ):
            raise ValueError(
                "occlusion evidence full inside mismatch must exceed its minimum"
            )
        if self.occlusion_ink_block_min_rows < 1:
            raise ValueError("occlusion ink block minimum rows must be positive")
        if self.occlusion_ink_block_max_gap < 0:
            raise ValueError("occlusion ink block maximum gap cannot be negative")
        if self.ecc_coarse_dimension < 64:
            raise ValueError("ecc_coarse_dimension must be at least 64")
        if self.ecc_working_dimension < 128:
            raise ValueError("ecc_working_dimension must be at least 128")
        if self.ecc_min_descriptor_matches < 0:
            raise ValueError("ecc_min_descriptor_matches cannot be negative")
        if self.automatic_link_max_numeric_filename_gap < 1:
            raise ValueError(
                "automatic_link_max_numeric_filename_gap must be positive"
            )
        if self.ecc_max_rotation_degrees <= 0:
            raise ValueError("ecc_max_rotation_degrees must be positive")
        if self.ecc_max_iterations < 1:
            raise ValueError("ecc_max_iterations must be positive")
        if self.ecc_epsilon <= 0:
            raise ValueError("ecc_epsilon must be positive")
        if (
            self.ecc_gaussian_filter_size < 1
            or self.ecc_gaussian_filter_size % 2 == 0
        ):
            raise ValueError("ecc_gaussian_filter_size must be a positive odd integer")
